included: # paths to include during linting. `--path` is ignored if present.
  - CoreData
  - VirtualCoin
  - VirtualCoinKit
analyzer_rules:
  - unused_import
  - unused_private_declaration
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - class_delegate_protocol
  - closure_end_indentation
  - closure_body_length
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition
line_length: 180
file_header:
required_pattern: |
                  \/\/
                  \/\/  .*?\.swift
                  \/\/  VCoin
                  \/\/
                  \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                  \/\/  Copyright © \d{4} Marcin Czachurski\. All rights reserved\.
                  \/\/
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
identifier_name:
  excluded: # excluded via string array
    - id
    - Id
    - x
    - y
