//
//  MarketList.swift
//  VCoinKit
//
//  Created by Marcin Czachurski on 27.01.2018.
//  Copyright © 2018 Marcin Czachurski. All rights reserved.
//

import Foundation

public class Markets {
    public static var allMarketsList = [
        Market(name: "Abucoins", code: "Abucoins"),
        Market(name: "ANXBTC", code: "ANXBTC"),
        Market(name: "Binance", code: "Binance"),
        Market(name: "Bit2C", code: "Bit2C"),
        Market(name: "BitBay", code: "BitBay"),
        Market(name: "Bitfinex", code: "Bitfinex"),
        Market(name: "bitFlyer", code: "bitFlyer"),
        Market(name: "bitFlyerFX", code: "bitFlyerFX"),
        Market(name: "Bithumb", code: "Bithumb"),
        Market(name: "BitMarket", code: "BitMarket"),
        Market(name: "Bitso", code: "Bitso"),
        Market(name: "BitSquare", code: "BitSquare"),
        Market(name: "Bitstamp", code: "Bitstamp"),
        Market(name: "BitTrex", code: "BitTrex"),
        Market(name: "Bleutrade", code: "Bleutrade"),
        Market(name: "BTC38", code: "BTC38"),
        Market(name: "BTCChina", code: "BTCChina"),
        Market(name: "BTCE", code: "BTCE"),
        Market(name: "BTCMarkets", code: "BTCMarkets"),
        Market(name: "btcXchange", code: "btcXchange"),
        Market(name: "BTCXIndia", code: "BTCXIndia"),
        Market(name: "BTER", code: "BTER"),
        Market(name: "BXinth", code: "BXinth"),
        Market(name: "CCCAGG", code: "CCCAGG"),
        Market(name: "CCEDK", code: "CCEDK"),
        Market(name: "CCEX", code: "CCEX"),
        Market(name: "Cexio", code: "Cexio"),
        Market(name: "CHBTC", code: "CHBTC"),
        Market(name: "Coinbase", code: "Coinbase"),
        Market(name: "Coincheck", code: "Coincheck"),
        Market(name: "Coinfloor", code: "Coinfloor"),
        Market(name: "Coinone", code: "Coinone"),
        Market(name: "Coinroom", code: "Coinroom"),
        Market(name: "Coinse", code: "Coinse"),
        Market(name: "Coinsetter", code: "Coinsetter"),
        Market(name: "Cryptopia", code: "Cryptopia"),
        Market(name: "CryptoX", code: "CryptoX"),
        Market(name: "Cryptsy", code: "Cryptsy"),
        Market(name: "EtherDelta", code: "EtherDelta"),
        Market(name: "EthexIndia", code: "EthexIndia"),
        Market(name: "Exmo", code: "Exmo"),
        Market(name: "Gatecoin", code: "Gatecoin"),
        Market(name: "Gateio", code: "Gateio"),
        Market(name: "Gemini", code: "Gemini"),
        Market(name: "HitBTC", code: "HitBTC"),
        Market(name: "Huobi", code: "Huobi"),
        Market(name: "HuobiPro", code: "HuobiPro"),
        Market(name: "itBit", code: "itBit"),
        Market(name: "Jubi", code: "Jubi"),
        Market(name: "Korbit", code: "Korbit"),
        Market(name: "Kraken", code: "Kraken"),
        Market(name: "LakeBTC", code: "LakeBTC"),
        Market(name: "Liqui", code: "Liqui"),
        Market(name: "LiveCoin", code: "LiveCoin"),
        Market(name: "LocalBitcoins", code: "LocalBitcoins"),
        Market(name: "Luno", code: "Luno"),
        Market(name: "Lykke", code: "Lykke"),
        Market(name: "MercadoBitcoin", code: "MercadoBitcoin"),
        Market(name: "MonetaGo", code: "MonetaGo"),
        Market(name: "MtGox", code: "MtGox"),
        Market(name: "Novaexchange", code: "Novaexchange"),
        Market(name: "OKCoin", code: "OKCoin"),
        Market(name: "OKEX", code: "OKEX"),
        Market(name: "Paymium", code: "Paymium"),
        Market(name: "Poloniex", code: "Poloniex"),
        Market(name: "QuadrigaCX", code: "QuadrigaCX"),
        Market(name: "Quoine", code: "Quoine"),
        Market(name: "Remitano", code: "Remitano"),
        Market(name: "TheRockTrading", code: "TheRockTrading"),
        Market(name: "Tidex", code: "Tidex"),
        Market(name: "TuxExchange", code: "TuxExchange"),
        Market(name: "Unocoin", code: "Unocoin"),
        Market(name: "Vaultoro", code: "Vaultoro"),
        Market(name: "ViaBTC", code: "ViaBTC"),
        Market(name: "WavesDEX", code: "WavesDEX"),
        Market(name: "Yacuna", code: "Yacuna"),
        Market(name: "Yobit", code: "Yobit"),
        Market(name: "Yunbi", code: "Yunbi"),
        Market(name: "Zaif", code: "Zaif")
    ]
}
